updated 4/28

diff --git a/.tox/venv/bin/ramdisk-image-create b/.tox/venv/bin/ramdisk-image-create
--- a/.tox/venv/bin/ramdisk-image-create
+++ b/.tox/venv/bin/ramdisk-image-create
@@ -25,10 +25,67 @@ export DIB_ARGS="$@"
 export DIB_ENV=$(export | grep ' DIB_.*=')
 
 SCRIPTNAME=$(basename $0)
-SCRIPT_HOME=$(dirname $(readlink -f $0))
-if [ -d $SCRIPT_HOME/../share/diskimage-builder ]; then
+
+# this is a bit tricky to handle the case of being installed with "pip
+# -e" (i.e. setuptools develop mode) and a regular install
+#
+# When installed normally, the scripts are installed into /usr/bin/
+# and the other bits specified in "data_files" into
+# /usr/share/diskimage-builder/[elements|lib|scripts] (if you're in a
+# virtualenv, modulo all this with the right prefix-paths)
+#
+# When installed with -e, the scripts will still be installed into
+# /usr/bin, but the data_files will *not* be installed.  Because the
+# "diskimage_builder" python module will be linked to the source repo
+# (that's the idea of develop mode) what we can do is assume the
+# following:
+#
+# - if the python module directory has a "bin" directory, then it must
+#   be the source repo and hence we have been installed via develop
+#   mode.  Thus setup ourselves to use the scripts from the source
+#   repo.
+#
+# - otherwise, try to find libraires and elements have been installed
+#   into the system paths via a "normal" pip install
+#
+# - lastly, we might be running completely uninstalled.
+#   XXX : this might cause problems at some point; we might need to "cd"
+#         so python can find things, or use pip -e.
+#
+# This means if you want to develop your elements, then "pip -e" is
+# the way to go ... your disk-image-create runs will be referencing
+# the scripts from the editable source repo.  But note that changes to
+# anything in bin/ will *not* be applied; those files have been
+# statically copied in during install.  You'll need to iterate with
+# another run of "pip install -e" if you're actually working on those
+# bin/* scripts.
+
+export SCRIPT_HOME=$(dirname $(readlink -f $0))
+
+_DIB_PYTHON_INSTALL=$(python -c '
+
+import inspect
+import os
+import sys
+
+# this can fail if we are being run with pwd outside the source
+# directory *and* have not been installed
+try:
+    import diskimage_builder
+except ImportError:
+    sys.exit(0)
+
+print(os.path.dirname(inspect.getfile(diskimage_builder)))')
+
+if [ -n "$_DIB_PYTHON_INSTALL"  -a -d $_DIB_PYTHON_INSTALL/../bin ]; then
+    # we have been installed with "pip -e"
+    export SCRIPT_HOME=$_DIB_PYTHON_INSTALL/../bin
+    export _PREFIX=$SCRIPT_HOME/..
+elif [ -d $SCRIPT_HOME/../share/diskimage-builder ]; then
+    # we have been installed in /usr
     export _PREFIX=$SCRIPT_HOME/../share/diskimage-builder
 else
+    # we have not been installed in any way
     export _PREFIX=$SCRIPT_HOME/..
 fi
 export _LIB=$_PREFIX/lib
@@ -45,10 +102,11 @@ function show_options () {
     echo "Options:"
     echo "    -a i386|amd64|armhf -- set the architecture of the image(default amd64)"
     echo "    -o imagename -- set the imagename of the output image file(default image)"
-    echo "    -t qcow2,tar,vhd,docker,raw -- set the image types of the output image files (default qcow2)"
+    echo "    -t qcow2,tar,vhd,docker,aci,raw -- set the image types of the output image files (default qcow2)"
     echo "       File types should be comma separated. VHD outputting requires the vhd-util"
-    echo "       executable be in your PATH."
-    echo "    -x -- turn on tracing"
+    echo "       executable be in your PATH. ACI outputting requires the ACI_MANIFEST "
+    echo "       environment variable be a path to a manifest file."
+    echo "    -x -- turn on tracing (use -x -x for very detailed tracing)"
     echo "    -u -- uncompressed; do not compress the image - larger but faster"
     echo "    -c -- clear environment before starting work"
     echo "    --image-size size -- image size in GB for the created image"
@@ -77,6 +135,7 @@ function show_options () {
         echo "    -p package[,package,package] -- list of packages to install in the image"
     fi
     echo "    -h|--help -- display this help and exit"
+    echo "    --version -- display version and exit"
     echo
     echo "ELEMENTS_PATH will allow you to specify multiple locations for the elements."
     echo
@@ -97,14 +156,23 @@ function show_options () {
     fi
 }
 
+function show_version() {
+    if [ -n "$_DIB_PYTHON_INSTALL" ]; then
+        python -c "from diskimage_builder import version; print(version.version_info.version_string())"
+    else
+        echo "diskimage-builder is not installed."
+    fi
+}
+
 INSTALL_PACKAGES=""
 IMAGE_TYPES=("qcow2")
 COMPRESS_IMAGE="true"
 export DIB_ROOT_LABEL=""
 DIB_DEFAULT_INSTALLTYPE=${DIB_DEFAULT_INSTALLTYPE:-"source"}
 MKFS_OPTS=""
+ACI_MANIFEST=${ACI_MANIFEST:-}
 DOCKER_TARGET=""
-TEMP=`getopt -o a:ho:t:xucnp: -l no-tmpfs,offline,help,min-tmpfs:,image-size:,image-cache:,max-online-resize:,mkfs-options:,qemu-img-options:,ramdisk-element:,root-label:,install-type:,docker-target: -n $SCRIPTNAME -- "$@"`
+TEMP=`getopt -o a:ho:t:xucnp: -l no-tmpfs,offline,help,version,min-tmpfs:,image-size:,image-cache:,max-online-resize:,mkfs-options:,qemu-img-options:,ramdisk-element:,root-label:,install-type:,docker-target: -n $SCRIPTNAME -- "$@"`
 if [ $? -ne 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
 # Note the quotes around `$TEMP': they are essential!
@@ -116,6 +184,7 @@ while true ; do
         -o) export IMAGE_NAME=$2; shift 2 ;;
         -t) IFS="," read -a IMAGE_TYPES <<< "$2"; export IMAGE_TYPES ; shift 2 ;;
         -h|--help) show_options; exit 0;;
+        --version) show_version; exit 0;;
         -x) shift; export DIB_DEBUG_TRACE=$(( $DIB_DEBUG_TRACE + 1 )); set -x;;
         -u) shift; export COMPRESS_IMAGE="";;
         -c) shift ; export CLEAR_ENV=1;;
@@ -195,6 +264,14 @@ for X in ${!IMAGE_TYPES[@]}; do
     esac
 done
 
+# NOTE: fstrim is on most all recent systems. It is provided by the util-linux
+# package.
+if [[ -z "$(which fstrim)" ]]; then
+    echo "fstrim utility is not found. This is provided by util-linux package"
+    echo "Please check your PATH variable is set correctly"
+    exit 1
+fi
+
 # NOTE: Tuning the rootfs uuid works only for ext filesystems.
 # Rely on the below environment variable only for ext filesystems.
 export DIB_IMAGE_ROOT_FS_UUID=$(uuidgen -r)
@@ -212,6 +289,15 @@ if [ -z "$DIB_ROOT_LABEL" ]; then
         DIB_ROOT_LABEL="img-rootfs"
     else
         DIB_ROOT_LABEL="cloudimg-rootfs"
+    fi
+fi
+
+# xattr support cannot be relied upon with tmpfs builds
+# some kernels supoprt it, some don't
+if [[ -n "${GENTOO_PROFILE}" ]]; then
+    if [[ "${GENTOO_PROFILE}" =~ "hardened" ]]; then
+        echo 'disabling tmpfs for gentoo hardened build'
+        export DIB_NO_TMPFS=1
     fi
 fi
 
@@ -237,13 +323,57 @@ fi
 unmount_image
 mv $TMP_BUILD_DIR/mnt $TMP_BUILD_DIR/built
 
+# save xtrace state, as we want to turn it off to avoid spamming the
+# logs with du output below.
+xtrace=$(set +o | grep xtrace)
+
 if [ -n "$DIB_IMAGE_SIZE" ]; then
-  du_size=$(echo "$DIB_IMAGE_SIZE" | awk '{printf("%d\n",$1 * 1024 *1024)}')
+    du_size=$(echo "$DIB_IMAGE_SIZE" | awk '{printf("%d\n",$1 * 1024 *1024)}')
 else
-  # in kb*0.60 - underreport to get a slightly bigger device
-  du_size=$(sudo du --block-size=600 -x -s ${TMP_BUILD_DIR}/built |\
-            awk ' { print $1 }')
+    set +o xtrace
+    echo "Calculating image size (this may take a minute)..."
+    du_output=$(sudo du -a -c -x ${TMP_BUILD_DIR}/built)
+    # the last line is the total size from "-c".
+    # scale this by 0.6 to create a slightly bigger image
+    du_size=$(echo "$du_output" | tail -n1 | cut -f1 | \
+                     awk '{print int($1 / 0.6)}')
+    $xtrace
 fi
+
+if [[ "${DIB_SHOW_IMAGE_USAGE:-0}" != 0 ]]; then
+    set +o xtrace
+    if [ -z "$du_output" ]; then
+        du_output=$(sudo du -a -c -x ${TMP_BUILD_DIR}/built)
+    fi
+
+    du_output_show="sort -nr |
+                     numfmt --to=iec-i --padding=7
+                       --suffix=B --field=1 --from-unit=1024"
+
+    # by default show the 10MiB and greater files & directories -- a
+    # dir with lots of little files will still show up, but this helps
+    # signal:noise ratio
+    if [[ ${DIB_SHOW_IMAGE_USAGE_FULL:-0} == 0 ]]; then
+        # numfmt will start giving a decimal place when < 10MiB
+        du_output_show+="| egrep 'MiB|GiB|TiB|PiB' | grep -v '\..MiB'"
+        echo "================================="
+        echo "Image size report (files > 10MiB)"
+        echo "================================="
+    else
+        echo "================="
+        echo "Image size report"
+        echo "================="
+    fi
+
+    eval ${du_output_show} <<< "$du_output"
+
+    echo
+    echo "===== end image size report ====="
+    echo
+
+    $xtrace
+fi
+
 if [ "$FS_TYPE" = "ext4" ] ; then
   # Very conservative to handle images being resized a lot
   # We set journal size to 64M so our journal is large enough when we
@@ -283,10 +413,23 @@ run_d_in_target finalise
 finalise_base
 
 for X in ${!IMAGE_TYPES[@]} ; do
-  if [ "${IMAGE_TYPES[$X]}" == "tar" ]; then
-    sudo tar -C ${TMP_BUILD_DIR}/mnt -cf $IMAGE_NAME.tar --exclude ./sys \
-             --exclude ./proc --xattrs --xattrs-include=\* .
-    sudo chown $USER: $IMAGE_NAME.tar
+  if [[ " tar aci " =~ "${IMAGE_TYPES[$X]}" ]]; then
+    if [ "${IMAGE_TYPES[$X]}" = "aci" ]; then
+      sudo tar -C ${TMP_BUILD_DIR}/mnt -cf $IMAGE_NAME.aci --exclude ./sys \
+               --exclude ./proc --xattrs --xattrs-include=\* \
+               --transform 's,^.,rootfs,S' .
+      if [ -n "$ACI_MANIFEST" ]; then
+        cp $ACI_MANIFEST ${TMP_BUILD_DIR}/manifest
+        sudo tar -C ${TMP_BUILD_DIR} --append -f $IMAGE_NAME.aci manifest
+      else
+        echo "No ACI_MANIFEST specified. An ACI_MANIFEST must be specified for"
+        echo " this image to be usable."
+      fi
+    else
+      sudo tar -C ${TMP_BUILD_DIR}/mnt -cf $IMAGE_NAME.tar --exclude ./sys \
+               --exclude ./proc --xattrs --xattrs-include=\* .
+    fi
+    sudo chown $USER: $IMAGE_NAME.${IMAGE_TYPES[$X]}
     unset IMAGE_TYPES[$X]
   elif [ "${IMAGE_TYPES[$X]}" == "docker" ]; then
     sudo tar -C ${TMP_BUILD_DIR}/mnt -cf - --exclude ./sys \
@@ -295,6 +438,9 @@ for X in ${!IMAGE_TYPES[@]} ; do
     unset IMAGE_TYPES[$X]
   fi
 done
+
+# Prep filesystem by discarding all unused space
+fstrim_image
 
 # Unmount and cleanup the /mnt and /build subdirectories, to save
 # space before converting the image to some other format.
diff --git a/.tox/venv/share/diskimage-builder/elements/growroot/static/usr/local/sbin/growroot b/.tox/venv/share/diskimage-builder/elements/growroot/static/usr/local/sbin/growroot
--- a/.tox/venv/share/diskimage-builder/elements/growroot/static/usr/local/sbin/growroot
+++ b/.tox/venv/share/diskimage-builder/elements/growroot/static/usr/local/sbin/growroot
@@ -5,16 +5,26 @@ set -exu
 set -o pipefail
 
 root_dev=$(df -P / | tail -n 1 | awk '/.*/ { print $1 }')
-minor_dev_no=$(stat --printf="%T" $root_dev)
-major_dev_no=$(stat --printf="%t" $root_dev)
 
-# The last digit of our minor number should, on a partitioned block device,
-# be the partition number of the device (starting at 1). We need to convert
-# this value to decimal from hex for use in growpart.
-part_no=$(echo $minor_dev_no | tail -c 2)
-part_no=$((16#$part_no))
+if [ -z "${root_dev}" ]; then
+    echo "*** Root device not found?"
+    exit 1
+fi
 
-disk=$(find /sys/dev/block -name "$((16#$major_dev_no)):${minor_dev_no::-1}0")
+udev_root=$(udevadm info --query=all --name $root_dev)
+
+part=$(grep ID_PART_ENTRY_DISK <<< "${udev_root}" | cut -d= -f2)
+if [ -z "${part}" ]; then
+    echo "*** Root partition not found!"
+    exit 1
+fi
+part_no=$(grep ID_PART_ENTRY_NUMBER <<< "${udev_root}" | cut -d= -f2)
+if [ -z "${part_no}" ]; then
+    echo "*** Root partition number not found!"
+    exit 1
+fi
+
+disk=$(find /sys/dev/block -name ${part})
 disk="/dev/$(source ${disk}/uevent; echo $DEVNAME)"
 
 set +e
diff --git a/.tox/venv/share/diskimage-builder/lib/common-functions b/.tox/venv/share/diskimage-builder/lib/common-functions
--- a/.tox/venv/share/diskimage-builder/lib/common-functions
+++ b/.tox/venv/share/diskimage-builder/lib/common-functions
@@ -173,7 +173,10 @@ function mount_qcow_image() {
 }
 
 function cleanup_build_dir () {
-    sudo rm -rf $TMP_BUILD_DIR/built
+    if ! timeout 5  sh -c " while ! sudo rm -rf $TMP_BUILD_DIR/built; do sleep 1; done"; then
+        echo "ERROR: unable to cleanly remove $TMP_BUILD_DIR/built"
+        exit 1
+    fi
     sudo rm -rf $TMP_BUILD_DIR/mnt
     if tmpfs_check 0; then
         sudo umount -f $TMP_BUILD_DIR || true
@@ -205,8 +208,9 @@ function detach_loopback() {
     # If setup on a rhel or derivative the map was created with kpartx not losetup
     # and subsequently needs to be removed.
     loopdev_name=$(echo $loopdev | sed 's/\/dev\///g')
-    mapper_name=$(sudo dmsetup ls | grep $loopdev_name | awk '{ print $1 }')
-    if [ "$mapper_name" ]; then
+
+    if sudo dmsetup ls | grep $loopdev_name; then
+        mapper_name=$(sudo dmsetup ls | grep $loopdev_name | awk '{ print $1 }')
         sudo dmsetup --noudevsync remove $mapper_name
     fi
 
@@ -277,12 +281,26 @@ function mount_proc_dev_sys () {
     sudo mount -t sysfs none $TMP_MOUNT_PATH/sys
 }
 
-function unmount_dir () {
-    local pattern="$1" mnts=""
-    if [ -n "$pattern" ]; then
-        mnts=`awk '{print $2}' < /proc/mounts | grep "^$pattern" | sort -r`
+# Recursively unmount directories under a given directory DIR
+# usage:
+#  unmount_dir DIR
+function unmount_dir {
+    local dir="$1"
+    local real_dir
+    local mnts
+
+    if [ ! -d $dir ]; then
+        echo "*** $dir is not a directory"
+        return 1
     fi
-    if [ -n "$mnts" ]; then
-        sudo umount -fl $mnts || true
-    fi
+
+    # get rid of any symlink elements in the incoming path, because
+    # /proc/mounts is the real path
+    real_dir=$(readlink -e $dir)
+
+    mnts=$(awk '{print $2}' < /proc/mounts | grep "^$real_dir" | sort -r)
+    for m in $mnts; do
+        echo "Unmount $m"
+        sudo umount -fl $m || true
+    done
 }
diff --git a/elements/hadoop-cloudera-s3a/install.d/51-patch-s3a b/elements/hadoop-cloudera-s3a/install.d/51-patch-s3a
--- a/elements/hadoop-cloudera-s3a/install.d/51-patch-s3a
+++ b/elements/hadoop-cloudera-s3a/install.d/51-patch-s3a
@@ -1,3 +1,23 @@
+#!/bin/bash
+
+if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
+    set -x
+fi
+set -eu
+set -o pipefail
+
+# Verify that we have patched JARs for this CDH version. 
+if [ $DIB_CDH_VERSION \< "5.4.5" ]; then
+  echo "Unsupported CDH version, accepted versions: 5.4.5"
+  exit -1
+fi
+
+# Skip patching if HDFS only image.
+if [ -n "${DIB_CDH_HDFS_ONLY:-}" ]; then
+  echo "No need to patch S3a on HDFS-only image."
+  exit
+fi
+
 # *** ATTENTION ***
 # Change this to point to your HTTP server. You can use Python's HTTP server:
 #   "python -m SimpleHTTPServer 80" 
@@ -5,3 +25,49 @@
 # the HTTP server. Open up a browser and go to S3A_PATCH_SERVER to verify that 
 # it's there.
 S3A_PATCH_SERVER=192.168.0.60:80
+
+# Patched Hadoop JARs repository, hardcoded for now.
+CDH_VERSION=5.4.5
+S3A_PATCH_DIR=s3a-jars-cdh-${CDH_VERSION}
+IMAGE_PATH=
+
+# Download patched JARs from a remote repository.
+S3A_PATCH_URL=http://${S3A_PATCH_SERVER}/${S3A_PATCH_DIR}
+cd /tmp
+wget -r -nH --no-parent --reject="index.html*" ${S3A_PATCH_URL}
+S3A_PATCH_PATH=/tmp/${S3A_PATCH_DIR}
+
+# Replace Hadoop JARs.
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/hadoop-aws-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/hadoop/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/hadoop-openstack-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/hadoop/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/common/hadoop-common-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/sqoop2/client-lib/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/common/hadoop-common-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/hadoop/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/mapreduce/hadoop-mapreduce-client-core-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/hadoop-mapreduce/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/mapreduce/hadoop-mapreduce-client-hs-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/hadoop-mapreduce/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-*-cdh${CDH_VERSION}-tests.jar ${IMAGE_PATH}/usr/lib/hadoop-mapreduce/
+
+# This is specific to Sahara's CDH file structure.
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/hadoop-openstack-*-cdh${CDH_VERSION}.jar ${IMAGE_PATH}/usr/lib/hadoop-mapreduce/hadoop-openstack.jar
+
+# Update Joda library.
+#cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/joda-time-*.jar ${CDH_PARCEL_PATH}/jars/
+
+# Replace AWS SDK.
+find ${IMAGE_PATH}/usr/lib -name 'aws-java-sdk*.jar' -delete
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/aws-java-sdk-*.jar ${IMAGE_PATH}/usr/lib/hadoop/lib/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/aws-java-sdk-*.jar ${IMAGE_PATH}/usr/lib/impala/lib/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/aws-java-sdk-*.jar ${IMAGE_PATH}/usr/lib/oozie/libtools/
+cp -f ${S3A_PATCH_PATH}/share/hadoop/tools/lib/aws-java-sdk-*.jar ${IMAGE_PATH}/usr/lib/parquet/lib/
+
+# Update all links to AWS SDK.
+cd ${IMAGE_PATH}/usr/lib/hadoop/client-0.20
+for f in $(ls ../lib/aws-java-sdk-*.jar); do
+  ln -s $f
+done
+cd ${IMAGE_PATH}/usr/lib/hadoop/client/
+for f in $(ls ../lib/aws-java-sdk-*.jar); do
+  ln -s $f
+done
+
+# Cleanup downloads.
+rm -rf ${S3A_PATCH_PATH}
